//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPO.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BPOEntities : DbContext
    {
        public BPOEntities()
            : base("name=BPOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_log_sistema> tbl_log_sistema { get; set; }
        public virtual DbSet<tbl_perfil_usuario> tbl_perfil_usuario { get; set; }
        public virtual DbSet<tbl_tipo_usuario> tbl_tipo_usuario { get; set; }
        public virtual DbSet<tbl_usuario> tbl_usuario { get; set; }
    }
}
