//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_log_sistema
    {
        public int id { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string acao { get; set; }
        public Nullable<System.DateTime> data_hora { get; set; }
        public string modulo { get; set; }
    
        public virtual tbl_usuario tbl_usuario { get; set; }
    }
}
