//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_usuario()
        {
            this.tbl_log_sistema = new HashSet<tbl_log_sistema>();
        }
    
        public int id { get; set; }
        public string nome { get; set; }
        public string password { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string username_session { get; set; }
        public Nullable<int> idTipo_Usuario { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_log_sistema> tbl_log_sistema { get; set; }
        public virtual tbl_tipo_usuario tbl_tipo_usuario { get; set; }
    }
}
