//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BPO.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_perfil_usuario
    {
        public int id { get; set; }
        public string modulo { get; set; }
        public string permissao { get; set; }
        public Nullable<int> idTipo_Usuario { get; set; }
    
        public virtual tbl_tipo_usuario tbl_tipo_usuario { get; set; }
    }
}
